server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/course_study?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    username: course
    password: zjj714705217
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8